### ISSUE TITLE
Wandb Issue 

### ISSUE THREAD

**Issue by elen211** [houssameehsain/BeadyRing_DRL#1]
Hello, @houssameehsain nice projects . I would like to ask a question for the Brouklyn- DeepRL. I downloaded  your code and  I’m trying to run the brooklyn_TDAC_GRU_wandbTUNE.py  but I have this error :
 wandb: Currently logged in as: elenleft  (eleni). Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: entity  not found during upsertBucket (<Response [404]>)
Thread SenderThread:
wandb: ERROR Internal wandb error: file data was not synced ". Is it possible to tell me how to fix it? Thank you in advance.

**Comment by houssameehsain** [comment]
Hi @elen211, did you try adding your own wandb login key?

**Comment by elen211** [comment]
Hello @houssameehsain  I did that but right now I can't train them.. It seems that every I do always has some issue with that wandb.

**Comment by houssameehsain** [comment]
Hey @elen211, I'm using wandb==0.12.18. Try this version, maybe it's an error related to your environment.
